### ISSUE TITLE
movingSum works strangely in Moira

### ISSUE THREAD

**Issue by syatihoko** [moira-alert/doc#88]
I am using moira 2.5.1.0. Function
movingSum works strangely in Moira.
In Grafana (source Graphite) is displayed correctly.
In Moira movingSum(), '15min') = approximately 1/2 movingSum(), '15min') in Grafana = movingSum(), 15) in Grafana.
Points at the graph every 30 seconds.

**Comment by syatihoko** [comment]
After testing, I realized that the problem is only when the local source (Redis). When Graphite is all good.
I tested with different targets - it looks like Redis is working incorrectly with this function.
I did not find a mention of this problem and its solution in new versions

**Comment by kissken** [comment]
Hello, @syatihoko! Thank you for issue! 

Could you describe, please, do you compare incoming data in both cases or only result?

And do you check with only time window "15min" or any else?

**Comment by syatihoko** [comment]
Hello. Thank you for responding. 
Yes, I checked, the original data is the same when compared. 
However, I did not go into the Redis database itself, I did not count the data (I probably need to do this). But other functions work correctly. There is one suspicion, I have data points every 30 seconds. It is possible that when working with Redis, points are calculated only once per minute. 
I checked different times up to 3 hour. The problem may not happen again if there are few points, for example, up to 10 marked points are displayed correctly.
The problems, at least, begin when it comes to thousands in the amount.

Repeated the tests:
![image](https://user-images.githubusercontent.com/52449706/196634541-be732455-6054-4a5a-956a-0f53eec37c46.png)

![image](https://user-images.githubusercontent.com/52449706/196637330-4db88fd5-66d2-4c4e-b03a-2d6eb74dbef0.png)

![image](https://user-images.githubusercontent.com/52449706/196635074-81508b54-e1ef-4349-bffc-f43379268908.png)

I also noticed that the function does not work at all by points, only by time. (I considered it as a workaround if it worked correctly):
![image](https://user-images.githubusercontent.com/52449706/196635466-db33be77-12ba-4210-9c3f-415a7fab2533.png)

**Comment by syatihoko** [comment]
![image](https://user-images.githubusercontent.com/52449706/196640705-c720fa8f-5ea3-4474-be92-3bbf11bcb55f.png)

![image](https://user-images.githubusercontent.com/52449706/196641759-3f8c568e-976b-49cf-a262-40e7b82ae6ee.png)


![image](https://user-images.githubusercontent.com/52449706/196641521-4af3c08e-e8e0-4917-a995-c08133ded6cb.png)

**Comment by syatihoko** [comment]
Sorry for disturbing. Looks like I found the reason. it was so and really the data was put only once a minute.
# cat storage-schemas.conf
```
[carbon]
pattern = ^carbon\.
retentions = 60:90d

[default_1min_for_1day]
pattern = .*
retentions = 60s:1d
```

Fix and now the sum roughly converges:
```
[carbon]
pattern = ^carbon\.
retentions = 30:90d

[default_1min_for_1day]
pattern = .*
retentions = 30s:1d
```
